### ISSUE TITLE
exoscale.toml created in the wrong directory on Windows

### ISSUE THREAD

**Issue by janoszen** [exoscale/cli#197]
When running `exo config` on Windows, the file in `C:\Users\USERNAME\.config\exoscale\exoscale.toml` is created with 0 bytes, and the actual `exoscale.toml` is created with the correct content in the current directory.

**Comment by pierre-emmanuelJ** [comment]
Thanks to post this issue 👍
We will try to reproduce the bug to solve it

**Comment by janoszen** [comment]
This issue seems to be fixed in git master on Windows 10 Pro.

**Comment by pierre-emmanuelJ** [comment]
Thank you!
Solved by: https://github.com/exoscale/cli/pull/193

**Comment by pierre-emmanuelJ** [comment]
On my side tested on Windows server 2019

**Comment by horakg** [comment]
looks like that bug still exists, just extracted exo cli 1.10.0 on my windows notebook to C:\users\mk6s56\mydrive\exo and did an "exo config" afterwards

C:\Users\mk6s56\myDrive\exo>exo config
No Exoscale CLI configuration found

Hi happy Exoscalian, some configuration is required to use exo.

We now need some very important information, find them there.
        <https://portal.exoscale.com/account/profile/api>

[+] API Key [none]: myapikey
[+] Secret Key [none]: mysecretkey
Retrieving account information... done!

[+] Name [a1-digital]:
v at-vie-1

exo vm list - is not possible as it complains about a missing configuration

C:\Users\mk6s56\myDrive\exo>exo vm list
no accounts were found into "C:\\Users\\mk6s56\\.config\\exoscale\\exoscale.toml"

If I manual select the correct exoscale.toml config it works
C:\Users\mk6s56\myDrive\exo>exo -C exoscale.toml vm list
┼──────────────────────────────────────┼─────────────────────────────────────────┼─────────────┼──────────┼─────────┼─────────────────┼
│                  ID                  │                  NAME                   │    SIZE     │   ZONE   │  STATE  │   IP ADDRESS    │
┼──────────────────────────────────────┼─────────────────────────────────────────┼─────────────┼──────────┼─────────┼─────────────────┼
│ a63888b9-2bec-4c1f-b9bf-f90857a8d744 │ westallianz-pentest                     │ Extra-large │ at-vie-1 │ Running │ 194.182.174.211 │
│ 665b082f-475a-4b97-b406-79f45b5305b4 │ HerwigDynDNS                            │ Micro       │ at-vie-1 │ Stopped │ 185.150.10.222  │
│ d225ce70-ddab-4ffd-ae58-e38e131b5129 │ GHO-W2K16-Client                        │ Extra-large │ at-vie-1 │ Running │ 185.150.10.210  │
│ d4bc782a-04c6-42c3-83ff-2a02ab5cc30e │ osbuilder2                              │ Huge        │ de-muc-1 │ Running │ 194.182.181.123 │
│ 5d9d601e-a20d-46ab-b906-70dcce69d07e │ lb2.openshift.a1.digital                │ Small       │ at-vie-1 │ Running │ 185.150.8.167   │

**Comment by greut** [comment]
If you're ready to adopt Go 1.13, [`os.UserConfigDir()`](https://godoc.org/os#UserConfigDir) should handle this correctly.

**Comment by pierre-emmanuelJ** [comment]
Thanks @greut I'll have a look to that 😉

**Comment by falzm** [comment]
@horakg we've just tried but failed to reproduce your issue on a Windows 10 system with the latest release of `exo`: it's unlikely that there is a regression in the code. Which Windows version are you using?

**Comment by horakg** [comment]
@falzm  on my windows 10 pc at home it works, will verify it again on my office laptop

On both pcs I just extracted the zip file to a folder and run exo config

**Comment by horakg** [comment]
@falzm attached the information from my windows 10 office pc
![image](https://user-images.githubusercontent.com/42831199/73745991-89073f80-4754-11ea-9de1-6af080c65557.png)

**Comment by falzm** [comment]
@horakg can you please try with this binary? https://github.com/exoscale/cli/pull/220#issuecomment-581781637

**Comment by pyr** [comment]
Fixed by #220, thanks for testing
